spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

server:
  servlet:
    context-path: /api

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid #id生成策略
      logic-delete-field: isDel
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



