spring:
  application:
    name: chat
  security:
    user:
      name: admin
      password: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    remote:
      restart:
        enabled: true
  data:
    redis:
      host: localhost #redis地址
      port: 6379 #redis端口
      database: 0 #redis数据库
      timeout: 10000 #redis超时时间
  jmx:
    enabled: false
server:
  servlet:
    context-path: /api


mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid #id生成策略
      logic-delete-field: isDel
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt-key: acd #加密盐值
token-expired-in: 86400000 #token过期时间

filepath: D:/chat/file/ #文件上传路径